http-server:
  # the IP address to host the HTTP and WebSocket server on.
  host: localhost

  # the port to host the HTTP and WebSocket server on.
  port: 65437

  # the URL for the WebSocket server. modify this for nginx servers
  websocket-url: "auto"

meta-info:
  # the welcome message players will see when accessing the web GUI
  welcome-msg: Welcome to proximity chat!

audio-settings:
  # how far away two players must be from each other (in blocks) to receive audio packets.
  activation-radius: 30
