name: Seraphwave
version: '0.1'
main: com.seraphwave.Plugin
api-version: '1.21'

commands:
   joinprox:
      description: Joins the proximity chat
      usage: /joinprox <code>
      permission: seraphwave.joinprox